// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfonkeqxcoleyowykhkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mb25rZXF4Y29sZXlvd3lraGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Njk1NDcsImV4cCI6MjA3MTI0NTU0N30.uNUH_-I27JAKnlxRVx54tYND729VQP4GfBMATqY2bJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});